### ISSUE TITLE
cmake error on ubuntu when linking fortran project with petsc

### ISSUE THREAD

**Issue by tjz2026** [jedbrown/cmake-modules#20]
Hi, I am trying to use cmake to compile our fortran project (don't ask why, I was to told to...), I am new to
cmake and I struggled days just to make mpi work..., now and I got the error as 

" CMake Error at cmake-modules/FindPETSC.cmake:171 (resolve_includes):
  Unknown CMake command "resolve_includes".
Call Stack (most recent call first):
  CMakeLists.txt:117 (find_package)"

I add a directory cmake-modules to put the files CorrectWindowsPaths.cmake, FindPETSc.cmake, FindPackageMultipass.cmake and ResolveCompilerPaths.cmake which I have gotten from you. 
and the following is my CMakeLists.txt on top level:

cmake_minimum_required (VERSION 2.6)
project (XXXX)
enable_language (Fortran CXX C)
find_package(MPI)
set(CMAKE_Fortran_COMPILE_FLAGS "${CMAKE_Fortran_COMPILE_FLAGS} ${MPI_Fortran_COMPILE_FLAGS}")
set(CMAKE_Fortran_LINK_FLAGS "${CMAKE_Fortran_LINK_FLAGS} ${MPI_Fortran_LINK_FLAGS}")
include_directories(SYSTEM ${MPI_Fortran_INCLUDE_PATH})
list (APPEND CMAKE_MODULE_PATH "./cmake-modules")
set (PETSC_DIR "/home/tjz/work/petsc-intel")
set (PETSC_ARCH "linux-gnu-gcc")
find_package(PETSC REQUIRED)
if(PETSC_FOUND)
    message(STATUS "Found Petsc:    ${PETSC_FOUND}" )
endif(PETSC_FOUND)

Could you please give me some help on solving this error, thank you very much!

**Comment by tjz2026** [comment]
solved~

**Comment by jedbrown** [comment]
That macro was defined in `ResolveCompilerPaths.cmake`. I assume something got lost or corrupted. Good to hear you solved your issue.
