### ISSUE TITLE
Use PETSc MPIEXEC for doing tests in FindPETSc.cmake?

### ISSUE THREAD

**Issue by rtmills** [jedbrown/cmake-modules#41]
On a machine like Summit at ORNL, executables built for the compute nodes need to be invoked via `jsrun`. I can get the tests that ship with PETSc to work by specifying `--with-mpiexec=jsrun -a 1 -c 1 -g 1` at configure time. I'm wondering if it might be a good idea to have the tests that are run by the FindPETSc.cmake module use the `MPIEXEC` that is specified in the PETSc configuration. This should allow the FindPETSc module to work on Summit, instead of having to force `PETSC_EXECUTABLE_RUNS` to `ON`.

I haven't written any CMake code in ten years and I don't remember how to do anything, so I don't know how hard it is to get CMake to grab the right things from the PETSc configuration or whether there might be some good reason to not want to do this.

Update: I'm messing with FindPETSc.cmake because a project I'm working on uses that. I now see that @jedbrown's `cmake-modules` README states that we should probably be using `FindPkgConfig` instead. I have not used this and don't know if it makes the above issue moot, or if it will run into the same issue. (Does it need to run anything?)

**Comment by jedbrown** [comment]
I'm not wild about having batch submission in the critical path. I'd also like to wean people's off this repository:
https://github.com/jedbrown/cmake-modules/commit/89cfd5088fa9362c63e15c6b346da9565f23e6a4

**Comment by rtmills** [comment]
Thanks, @jedbrown. I will try to move this project to using `FindPkgConfig`.
